services:
  - type: web
    name: api-32-0sku
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecologico_monitor.src.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0